// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package mostliked

type Lang struct {
	Uri  string
	Lang string
}

type Post struct {
	Uri      string
	CreateTs int64
	Likes    int64
}
